// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8BNI8Xyc8JFYv7MKuyx4j_-oMKsxdN4',
    appId: '1:348275640838:web:149effe803bca94b2bd187',
    messagingSenderId: '348275640838',
    projectId: 'pushnotification-ebd63',
    authDomain: 'pushnotification-ebd63.firebaseapp.com',
    storageBucket: 'pushnotification-ebd63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3qZF52s4btVtUJtGtViQOpq1losKynw',
    appId: '1:348275640838:android:38150672c8ad8bea2bd187',
    messagingSenderId: '348275640838',
    projectId: 'pushnotification-ebd63',
    storageBucket: 'pushnotification-ebd63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJo0c2N72cDLXy8PiBBpOSvL92P3tikQ',
    appId: '1:348275640838:ios:d00a07ee8855a2f62bd187',
    messagingSenderId: '348275640838',
    projectId: 'pushnotification-ebd63',
    storageBucket: 'pushnotification-ebd63.appspot.com',
    iosClientId: '348275640838-g0hqe115th7jg7nhd6anfrp1n3f5conf.apps.googleusercontent.com',
    iosBundleId: 'com.example.methodchannelprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJo0c2N72cDLXy8PiBBpOSvL92P3tikQ',
    appId: '1:348275640838:ios:14a078f42e662d982bd187',
    messagingSenderId: '348275640838',
    projectId: 'pushnotification-ebd63',
    storageBucket: 'pushnotification-ebd63.appspot.com',
    iosClientId: '348275640838-kbajrfdoq9ba8upuulbb103ts03chshd.apps.googleusercontent.com',
    iosBundleId: 'com.example.methodchannelprojects.RunnerTests',
  );
}
